navigate:
  name: Navigate to a view
  description: >
    Command device to navigate to a certain view
  fields:
    device:
      name: Device
      description: The device to change screen on
      example: "123434"
      required: true
      selector:
        entity:
          filter:
            integration: view_assist
    path:
      name: View Path
      description: Path in dashboard view
      example: "/view-assist/clock"
      required: true
      selector:
        text:
set_state:
  name: Set state or attributes
  description: >
    Set state or attributes of View Assist entity
  target:
    entity:
      integration: view_assist
      domain:
        - sensor
  fields:
    state:
      name: "State"
      description: "Entity state"
      selector:
        text:
set_timer:
  name: Set a timer
  description: Set an alarm, timer or reminder
  fields:
    entity_id:
      name: "Entity ID"
      description: "Entity id of the View Assist entity"
      required: false
      selector:
        entity:
          integration: view_assist
          domain:
            - sensor
    device_id:
      name: "Device ID"
      description: "Device id of the voice satellite"
      required: false
      selector:
        device:
    type:
      name: "Timer type"
      description: "The type of timer - alarm, timer, reminder, command"
      required: true
      selector:
        select:
          options:
            - "Alarm"
            - "Timer"
            - "Reminder"
            - "Command"
    name:
      name: "Name"
      description: "The name of the timer"
      required: false
      selector:
        text:
    time:
      name: "Time sentence"
      description: "A spoken like time sentence"
      required: true
      selector:
        text:
    language:
      name: Language
      description: The desired language to analyze the time sentence
      default: en
      selector:
        select:
          mode: dropdown
          options:
            - label: English
              value: en
cancel_timer:
  name: "Cancel timer"
  description: "Cancel running timer"
  fields:
    timer_id:
      name: "Timer ID"
      description: "The id of the timer"
      required: false
      selector:
        text:
    entity_id:
      name: "Entity ID"
      description: "Entity id of the View Assist entity"
      required: false
      selector:
        entity:
          integration: view_assist
          domain:
            - sensor
    device_id:
      name: "Device ID"
      description: "The id of the voice satellite device to cancel all timers for"
      required: false
      selector:
        device:
    remove_all:
      name: "Remove all"
      description: "Cancel all timers"
      required: false
      selector:
        boolean:
get_timers:
  name: "Get timers"
  description: "Get all timers or by timer id or device id"
  fields:
    timer_id:
      name: "Timer ID"
      description: "The id of the timer"
      required: false
      selector:
        text:
    entity_id:
      name: "Entity ID"
      description: "Entity id of the View Assist entity"
      required: false
      selector:
        entity:
          integration: view_assist
          domain:
            - sensor
    device_id:
      name: "Device ID"
      description: "The id of the voice satellite device to get all timers for"
      required: false
      selector:
        device:
    name:
      name: "Name"
      description: "The name of the timer"
      required: false
      selector:
        text:
snooze_timer:
  name: Snooze a timer
  description: Snooze an expired timer for a certain time
  fields:
    timer_id:
      name: "Timer id"
      description: "The id of the timer"
      required: true
      selector:
        text:
    time:
      name: "Snooze duration"
      description: "The snooze duration in a sentence (e.g. 5 minutes)"
      required: true
      selector:
        text:
    language:
      name: Language
      description: The desired language to analyze the snooze duration
      default: en
      selector:
        select:
          mode: dropdown
          options:
            - label: English
              value: en
sound_alarm:
  name: "Sound alarm"
  description: "Sound alarm on a media device with an attempt to restore any already playing media"
  fields:
    entity_id:
      name: "Entity ID"
      description: "The media player to play the alarm on"
      required: true
      selector:
        entity:
          domain:
            - media_player
    media_file:
      name: "Media file"
      description: "Media file to use for alarm"
      required: true
      selector:
        text:
    max_repeats:
      name: "Max repeats"
      description: "The maximun number of times to repeat the alarm media file"
      required: false
      selector:
        number:
cancel_sound_alarm:
  name: "Cancel sound alarm"
  description: "Cancel a sounding alarm"
  fields:
    entity_id:
      name: "Entity ID"
      description: "The media player to cancel the alarm on"
      required: false
      selector:
        entity:
          domain:
            - media_player
broadcast_event:
  name: "Broadcast Event"
  description: "Send a custom event"
  fields:
    event_name:
      name: "Event name"
      description: "The name of the event"
      required: true
      selector:
        text:
    event_data:
      name: "Event data"
      description: "The event data variables to include in the event broadcast"
      required: true
      selector:
        text:
load_view:
  name: "Load View"
  description: "Install a view from the View Assist views directory or repository"
  fields:
    name:
      name: "View name"
      description: "The name of the view"
      required: true
      selector:
        text:
    download_from_repo:
      name: "Download from respository"
      description: "Download from the github repository, overwriting any existing copy"
      required: false
      default: false
      selector:
        boolean:
    community_view:
      name: "Community view"
      description: "If this should be downloaded from the community views folder"
      required: false
      default: false
      selector:
        boolean:
    backup_current_view:
      name: "Backup current view"
      description: "Backup yaml of view if it exists before updating"
      required: false
      default: false
      selector:
        boolean:
save_view:
  name: "Save View"
  description: "Save a view to the View Assist views directory"
  fields:
    name:
      name: "View name"
      description: "The name of the view"
      required: true
      selector:
        text:
